export enum Settings {
  'channels' = 'channels',
  'username' = 'nickname',
  'highlightColor' = 'highlightColor',
  'highlightBorder' = 'highlightBorder',
  'highlightFontColor' = 'highlightFontColor',
  'autoConnect' = 'autoConnect',
  'announceBot' = 'announceBot',
  'joinMessage' = 'joinMessage',
  'leaveMessage' = 'leaveMessage',
  'unhighlightOnDisconnect' = 'unhighlightOnDisconnect',
  'showHighlightsInActivityBar' = 'showHighlightsInActivityBar',
  'usageTip' = 'usageTip',
  'requiredBadges' = 'requiredBadges',
  'switchActiveTab' = 'switchActiveTab',
}
