name: 'Build and Test'

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Run tests
        shell: bash
        run: |
          set +e

          if [[ "$RUNNER_OS" == "Linux" ]]; then
            CMD="xvfb-run -a bun vscode:test"
          else
            CMD="bun vscode:test"
          fi

          eval "$CMD"
          EXIT_CODE=$?

          echo "🔍 VSCode test runner exit code: $EXIT_CODE"

          if [ $EXIT_CODE -eq 0 ]; then
            echo "✅ Tests passed!"
            exit 0
          else
            echo "❌ Tests failed (exit $EXIT_CODE)"
            exit $EXIT_CODE
          fi
